### ISSUE TITLE
move issues from kanbanflow to github-projects

### ISSUE THREAD

**Issue by Inkimar** [CGI-NRM/SeqDB-documentation#1]
https://kanbanflow.com/board/WdbaHn4L

**Comment by thokall** [comment]
I have started to import some of the issues but as own issues here. Some of the comments are not easy to follow. Do we have notes on our discussions elsewhere?

**Comment by thokall** [comment]
The once I feel are moved here as a new issue are moved to done in the kanban project. The rest I am not sure what to do with.

**Comment by thokall** [comment]
We have everything we want here at github now so this issue can be closed

**Comment by Inkimar** [comment]
https://kanbanflow.com/board/WdbaHn4L has been deleted.
