### ISSUE TITLE
new use-case (2018-08-22) 

### ISSUE THREAD

**Issue by Inkimar** [CGI-NRM/SeqDB-documentation#32]
Create a new use-case, create a template from seqdb as a baseline - go from there.

Which Attributes should be uploaded ?

**Comment by Gyllenstrand** [comment]
The template Thomas did was fine

**Comment by Inkimar** [comment]
@thokall , will you save that template in the repo ?

**Comment by thokall** [comment]
See commit b3a6cdb410ec434aa853e2f6db0770210fb983ad
